import { algo } from '@dsims/engine';

export type DemoKind = 'algorithms' | 'patterns' | 'network' | 'machine' | 'languages' | 'ai';

const ICON: Record<string, string> = {
  'ai-linalg': 'grid-3x3',
  'ai-ml': 'chart-scatter',
  'ai-langchain': 'link',
  'ai-langgraph': 'workflow',
  'ai-attention': 'grid-3x3',
  'ai-block-deep': 'layers',
  'algo-two-pointers': 'move-horizontal',
  'algo-sliding-window': 'scan',
  'algo-binary-search': 'search',
  'algo-prefix-hash': 'hash',
  'algo-stack': 'layers',
  'algo-heap': 'triangle',
  'algo-linked-list': 'link',
  'algo-trees': 'git-branch',
  'algo-graphs': 'share-2',
  'algo-trie': 'list-tree',
  'algo-backtracking': 'undo-2',
  'algo-dp': 'table',
  'algo-greedy': 'calendar-range',
  'algo-math': 'sigma',
  'algo-design': 'box',
  'machine-os-boot': 'power',
  'machine-os-process': 'list-tree',
  'machine-os-fs': 'folder-tree',
  'machine-os-perm': 'shield',
  'machine-os-containers': 'container',
  'machine-os-virt': 'server',
  'machine-os-docker': 'package',
  'machine-os-k8s': 'ship-wheel',
  'machine-os-shell': 'square-terminal',
  'git-internals': 'git-branch',
  'stack-kafka': 'scroll-text',
  'stack-spark': 'sparkles',
  'stack-airflow': 'wind',
  'stack-dagster': 'layers',
  'stack-dbt': 'table',
  'stack-databricks': 'waves',
  'stack-postgres': 'database',
  'ai-neuralnet': 'brain',
  'ai-tokenizer': 'text-cursor-input',
  'ai-embeddings': 'scatter-chart',
  'ai-transformer': 'sparkles',
  'ai-training': 'trending-down',
  'ai-finetune': 'sliders-horizontal',
  'ai-rlhf': 'thumbs-up',
  'ai-quant': 'minimize-2',
  'ai-inference': 'play',
  'ai-serving': 'server',
  'ai-speculative': 'fast-forward',
  'ai-gpu': 'cpu',
  'ai-rag': 'book-open-check',
  'ai-agents': 'bot',
  'ai-eval': 'clipboard-check',
  'sd-txn': 'git-merge',
  'sd-caching': 'database-zap',
  'sd-consistency': 'copy',
  'sd-ratelimit': 'gauge',
  'sd-mq': 'inbox',
  'sd-migration': 'arrow-right-left',
  'sd-auth': 'key-round',
  'sd-arch': 'boxes',
  'sd-chat': 'message-circle',
  'sd-video': 'clapperboard',
  'sd-frontend': 'layout-panel-top',
  'sd-serverless': 'cloud-lightning',
  'sd-telemetry': 'activity',
  'sd-vpc': 'cloud',
  Graph: 'route',
  Partitioning: 'circle-dashed',
  Geo: 'map-pin',
  Probabilistic: 'dices',
  Storage: 'database',
  Distributed: 'network',
  'Rate limit': 'gauge',
  'machine-cpu': 'cpu',
  'machine-memory': 'memory-stick',
  'machine-bus': 'circuit-board',
  'machine-asm': 'binary',
  'machine-bits': 'toggle-right',
  'machine-cpp': 'braces',
  'cpp-basics': 'braces',
  'cpp-oop': 'boxes',
  'cpp-stl': 'library',
  'cpp-modern': 'sparkles',
  'cpp-concurrency': 'git-fork',
  'cpp-cmake': 'hammer',
  'cpp-projects': 'network',
  'cpp-patterns': 'shapes',
  'cpp-network': 'server',
  'lang-go': 'zap',
  'lang-python': 'terminal',
  'lang-java': 'coffee',
  'lang-rust': 'cog',
  'lang-csharp': 'hash',
  'lang-fp': 'lambda',
  'lang-lua': 'moon',
  'tech-kafka': 'scroll-text',
  'tech-spark': 'flame',
  tdd: 'flask-conical',
  'net-layers': 'layers',
  'net-link': 'cable',
  'net-ip': 'route',
  'net-tcp': 'arrow-left-right',
  'net-quic': 'zap',
  'net-dns': 'signpost',
  'net-http': 'globe',
  'net-tls': 'lock',
  'net-lb': 'split',
  'net-tools': 'wrench',
};

const LABEL: Record<string, string> = {
  'ai-linalg': 'Linear algebra',
  'ai-ml': 'ML basics',
  'ai-langchain': 'LangChain',
  'ai-langgraph': 'LangGraph',
  'ai-attention': 'Attention, step by step',
  'ai-block-deep': 'Transformer block',
  'algo-two-pointers': 'Two pointers',
  'algo-sliding-window': 'Sliding window',
  'algo-binary-search': 'Binary search',
  'algo-prefix-hash': 'Prefix sums & hashing',
  'algo-stack': 'Stack & monotonic stack',
  'algo-heap': 'Heap / top-k',
  'algo-linked-list': 'Linked list tricks',
  'algo-trees': 'Trees: BFS & DFS',
  'algo-graphs': 'Graphs',
  'algo-trie': 'Trie',
  'algo-backtracking': 'Backtracking',
  'algo-dp': 'Dynamic programming',
  'algo-greedy': 'Greedy & intervals',
  'algo-math': 'Math & number theory',
  'algo-design': 'Object design',
  'machine-os-boot': 'Boot process',
  'machine-os-process': 'Processes & signals',
  'machine-os-fs': 'Filesystems',
  'machine-os-perm': 'Permissions',
  'machine-os-containers': 'Namespaces & containers',
  'machine-os-virt': 'VMs & hypervisors',
  'machine-os-docker': 'Docker',
  'machine-os-k8s': 'Kubernetes node',
  'machine-os-shell': 'Shell & make',
  'git-internals': 'Git internals',
  'stack-kafka': 'Kafka ops',
  'stack-spark': 'Spark',
  'stack-airflow': 'Airflow',
  'stack-dagster': 'Dagster',
  'stack-dbt': 'dbt',
  'stack-databricks': 'Databricks & Delta',
  'stack-postgres': 'Postgres HA & migration',
  'ai-neuralnet': 'Neural networks',
  'ai-tokenizer': 'Tokenization',
  'ai-embeddings': 'Embeddings',
  'ai-transformer': 'Transformer',
  'ai-training': 'Pretraining',
  'ai-finetune': 'Fine-tuning',
  'ai-rlhf': 'RLHF & DPO',
  'ai-quant': 'Quantization',
  'ai-inference': 'Decoding & KV cache',
  'ai-serving': 'Inference servers',
  'ai-speculative': 'Speculative decoding',
  'ai-gpu': 'GPU',
  'ai-rag': 'RAG',
  'ai-agents': 'Agents',
  'ai-eval': 'Evaluation',
  'sd-txn': 'Transactions',
  'sd-caching': 'Caching',
  'sd-consistency': 'Consistency',
  'sd-ratelimit': 'Rate limiting',
  'sd-mq': 'Delivery guarantees',
  'sd-migration': 'Migration',
  'sd-auth': 'Authentication',
  'sd-arch': 'Architecture',
  'sd-chat': 'Live chat',
  'sd-video': 'Video streaming',
  'sd-frontend': 'Frontend',
  'sd-serverless': 'Serverless',
  'sd-telemetry': 'Telemetry',
  'sd-vpc': 'Cloud networking',
  'machine-cpu': 'CPU',
  'machine-memory': 'Memory',
  'machine-bus': 'Chips, buses & I/O',
  'machine-asm': 'Assembly',
  'machine-bits': 'Bit manipulation',
  'machine-cpp': 'C++ under the hood',
  'cpp-basics': 'C++ basics',
  'cpp-oop': 'Classes & OOP',
  'cpp-stl': 'STL',
  'cpp-modern': 'Modern C++',
  'cpp-concurrency': 'Concurrency',
  'cpp-cmake': 'CMake',
  'cpp-projects': 'Large projects',
  'cpp-patterns': 'Design patterns',
  'cpp-network': 'C++ network servers',
  'lang-go': 'Go',
  'lang-python': 'Python',
  'lang-java': 'Java',
  'lang-rust': 'Rust',
  'lang-csharp': 'C#',
  'lang-fp': 'Functional programming',
  'lang-lua': 'Lua in nginx & Redis',
  'tech-kafka': 'Kafka internals',
  'tech-spark': 'Spark internals',
  tdd: 'Test-driven development',
  'net-layers': 'Layers & encapsulation',
  'net-link': 'Ethernet & ARP',
  'net-ip': 'IP & routing',
  'net-tcp': 'TCP',
  'net-quic': 'UDP & QUIC',
  'net-dns': 'DNS',
  'net-http': 'HTTP & real-time',
  'net-tls': 'TLS',
  'net-lb': 'Load balancers & CDNs',
  'net-tools': 'Debugging tools',
};

export const KIND_LABEL: Record<DemoKind, string> = { algorithms: 'Distributed algorithms', network: 'Network', machine: 'Machine level', languages: 'Languages', ai: 'Machine learning & LLMs', patterns: 'Algorithms' };

export const kindOf = (g: string): DemoKind => (g.startsWith('ai-') ? 'ai' : g.startsWith('algo-') ? 'patterns' : g === 'machine-cpp' || g.startsWith('cpp-') || g.startsWith('lang-') ? 'languages' : g.startsWith('net-') ? 'network' : g.startsWith('machine') ? 'machine' : 'algorithms');
export const groupIcon = (g: string) => ICON[g] ?? (g.startsWith('net-') ? 'network' : 'diamond');
/** Known label, else the id without its prefix, capitalised (`net-tcp` → `Tcp`). */
export const groupLabel = (g: string) => LABEL[g] ?? (g.includes('-') ? g.slice(g.indexOf('-') + 1) : g).replace(/-/g, ' ').replace(/^./, ch => ch.toUpperCase());

export interface DemoGroup {
  id: string;
  kind: DemoKind;
  label: string;
  icon: string;
  demos: algo.Demo[];
}

const KIND_ORDER: DemoKind[] = ['algorithms', 'patterns', 'network', 'machine', 'languages', 'ai'];

/** All demo groups, algorithms → network → machine → languages, in registration order within each kind. */
export function demoGroups(): DemoGroup[] {
  const by = new Map<string, algo.Demo[]>();
  for (const d of algo.allDemos()) by.set(d.group, [...(by.get(d.group) ?? []), d]);
  return [...by.entries()]
    .map(([id, demos]) => ({ id, kind: kindOf(id), label: groupLabel(id), icon: groupIcon(id), demos }))
    .sort((a, b) => KIND_ORDER.indexOf(a.kind) - KIND_ORDER.indexOf(b.kind));
}
