// content/ YAML + JSON + SVG -> content/dist/*.json + index.ts. Usage: node scripts/build-content.mjs [--lenient]
import fs from 'node:fs';
import path from 'node:path';
import { CONTENT, buildCatalog, loadContent, report, smoke, validate } from './validate-content.mjs';

const DIST = path.join(CONTENT, 'dist');

// drop loader bookkeeping (__file) and yaml anchors
const clean = (v) => JSON.parse(JSON.stringify(v, (k, x) => (k.startsWith('__') ? undefined : x)));

smoke();
const c = loadContent(CONTENT, { lenient: process.argv.includes('--lenient') });
if (!report(validate(c))) {
  console.error('content build failed');
  process.exit(1);
}

const byOrder = (a, b) => (a.order ?? 99) - (b.order ?? 99);
const out = {
  'catalog.json': buildCatalog(c),
  'chaos.json': c.chaos,
  'traffic.json': { shapes: c.traffic.shapes ?? [], presets: c.traffic.presets ?? [] },
  'icons.json': c.icons,
  'templates.json': c.templates,
  'topics.json': [...c.topics].sort(byOrder),
  'problems.json': [...c.problems].sort(byOrder),
  'tech.json': c.tech,
};

fs.mkdirSync(DIST, { recursive: true });
for (const [name, data] of Object.entries(out)) fs.writeFileSync(path.join(DIST, name), JSON.stringify(clean(data)));
fs.writeFileSync(path.join(DIST, 'index.ts'), INDEX_TS());

for (const f of [...Object.keys(out), 'index.ts']) {
  const kb = (fs.statSync(path.join(DIST, f)).size / 1024).toFixed(1);
  console.log(`  content/dist/${f.padEnd(15)} ${kb.padStart(7)} KB`);
}

function INDEX_TS() {
  return `// Generated by scripts/build-content.mjs — do not edit.
import type { Catalog, ContainerKind, Knob, MetricKey, SystemDoc, TrafficEvent, TrafficShape } from '../../engine/src/types';
import catalogJson from './catalog.json';
import chaosJson from './chaos.json';
import trafficJson from './traffic.json';
import iconsJson from './icons.json';
import templatesJson from './templates.json';
import topicsJson from './topics.json';
import problemsJson from './problems.json';
import techJson from './tech.json';

export interface GroupDef {
  id: string;
  label: string;
  order: number;
}

export interface ContainerDef {
  kind: ContainerKind;
  label: string;
  icon: string;
  /** header chip glyph */
  chip: string;
  description: string;
  knobs: Knob[];
}

export type ContentCatalog = Catalog & { groups: GroupDef[]; containers: ContainerDef[] };

export type ChaosGroup = 'Node' | 'Network' | 'Data' | 'Time' | 'Traffic' | 'Infra' | 'Security' | 'Protocol';
export type ChaosTarget = 'node' | 'edge' | 'pair' | 'container' | 'source' | 'none';

export interface ChaosDef {
  kind: string;
  label: string;
  description: string;
  group: ChaosGroup;
  icon: string;
  emoji: string;
  target: ChaosTarget;
  /** engine types / container kinds, or 'any' */
  appliesTo: string[] | 'any';
  params: Knob[];
  /** null = until healed; 0 = instantaneous */
  defaultDurationSec: number | null;
  /** fire as a TrafficEvent on a source; scale multiplies params (e.g. % -> fraction) */
  traffic?: { action: TrafficEvent['action']; whenTarget?: 'source'; scale?: Record<string, number> };
}

export interface TrafficShapeDef {
  kind: TrafficShape['kind'];
  label: string;
  icon: string;
  params: Knob[];
}

export interface TrafficPreset {
  id: string;
  label: string;
  icon: string;
  emoji: string;
  event: Omit<TrafficEvent, 'kind' | 'source'>;
}

export interface LessonDef {
  id: string;
  title: string;
  minutes: number;
  template?: string;
  algo?: string;
  steps: {
    title: string;
    body: string;
    watch?: string;
    /** algo lessons: demo input id this step switches to */
    input?: string;
    check?: { metric: MetricKey; target?: string; op: '<' | '<=' | '>=' | '>' | '='; value: number };
  }[];
}

export interface TopicDef {
  id: string;
  title: string;
  group: 'topics' | 'under-the-hood' | 'network' | 'machine' | 'languages' | 'ai' | 'patterns';
  /** languages group only */
  language?: 'cpp' | 'go' | 'python' | 'java' | 'rust' | 'csharp' | 'fp';
  icon: string;
  summary: string;
  order: number;
  lessons: LessonDef[];
}

export interface ProblemDef {
  id: string;
  title: string;
  icon: string;
  category: 'classic' | 'product' | 'infra';
  order: number;
  summary: string;
  requirements: string[];
  estimates: string[];
  designs: { id: 'v1' | 'v2'; title: string; template: string }[];
  challenges: { id: string; title: string; template?: string; scenario?: any; pass: any[] }[];
  keyIdeas: { label: string; link?: string }[];
}

export interface TechDef {
  id: string;
  title: string;
  summary: string;
  template: string;
  lessons: LessonDef[];
}


export const catalog = catalogJson as unknown as ContentCatalog;
export const chaos = chaosJson as unknown as ChaosDef[];
export const traffic = trafficJson as unknown as { shapes: TrafficShapeDef[]; presets: TrafficPreset[] };
export const icons = iconsJson as unknown as Record<string, string>;
export const templates = templatesJson as unknown as Record<string, SystemDoc>;
export const topics = topicsJson as unknown as TopicDef[];
export const problems = problemsJson as unknown as ProblemDef[];
export const tech = techJson as unknown as TechDef[];
`;
}
